### ISSUE TITLE
Google Chrome display irregularities

### ISSUE THREAD

**Issue by joeyfromspace** [nckprsn/scrollme#20]
Starting about one month ago, I've noticed that ScrollMe animations have become glitchy in Chrome for both Android and Windows.

More specifically, the animated elements are duplicated with the original element never disappearing, so even if an element is supposed to scroll out of view, it remains on the page. Also when it is animating in view, the element is already at the destination, creating a strange ghosting appearance. At first I thought this was an error on my part, but I noticed it happening on the ScrollMe homepage as well.

See screenshot to get an idea of what I mean. I haven't tried to see if the issue is also present in IE or Firefox.

![screenshot_2014-12-27-10-02-06](https://cloud.githubusercontent.com/assets/6892103/5561590/93fe57c0-8daf-11e4-8b52-3b495852ac6e.png)

**Comment by iljapanic** [comment]
I'm having the same issue in Chrome (*39.0.2171.99*).

It worked perfectly fine when I started using the plugin and just started seeing the issue now. Also, it's very hard to replicate consistently. It simply sometimes appears and sometimes it does not.
 
![image](https://cloud.githubusercontent.com/assets/1295321/5837503/092b1568-a180-11e4-9874-347abbf4ca1c.png)

**Comment by dmi90** [comment]
This problem seems to be related to Chrome only indeed. Setting "position: relative" to the element getting scrolled solved this one for me.
