### ISSUE TITLE
Identifies scrollme element, initialises, but doesn't animate

### ISSUE THREAD

**Issue by chriddell** [nckprsn/scrollme#41]
Hi Nick,

Example here: http://approvalarea.com/scrollme-test/

I can't explain much better than if you visit the link and see the demo in action (or, non-action). Scrollme seems to initialise, the console throws no errors, however the animateme element simply doesn't animate. I've copied the code exactly as is from your Codepen example (http://codepen.io/nckprsn/pen/IGpmc) just to make sure it wasn't something I had done in my custom code, however it still doesn't fire!

Has anyone idea what's going on here? Have tested on multiple versions of multiple browsers (Safari, Firefox, Chrome).

**Comment by chriddell** [comment]
Update: I'm an idiot. My HTML didn't declare its doctype, and adding this fixed it!

**Comment by derosaav** [comment]
Thanks, @chriddell, I just ran into the same issue, and your post helped me get through it!
