### ISSUE TITLE
Scrollme on mobile devices

### ISSUE THREAD

**Issue by doublevv** [nckprsn/scrollme#9]
Hi !

This great plugin does not work really smoothy with iPhone or iPad... Is there a way to make this point better ? 

Or can we at least desactivate those animations on selected devices ?

Thanks a lot !

**Comment by SerzN1** [comment]
@poopsplat, 
`scrollme.init_if = !Modernizr.touch;`

**Comment by poopsplat** [comment]
@SerzN1 nice!

**Comment by SerzN1** [comment]
@poopsplat, but error working. Realy 
`scrollme.init_if = function() { return !Modernizr.touch;}`
